server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.91.100
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
  redis:
    host: 192.168.91.100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
ly:
  jwt:
    pubKeyPath: C:/tmp/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  worker:
    workerId: 1
    datacenterId: 1
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl: http://jzm34n.natappfree.cc/notify/pay
