server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.91.100
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.91.100
ly:
  sms:
    accessKeyId: LTAI4Fe6Y92BKnNsnXHCYLrF    # 你自己的accessKeyId
    accessKeySecret: izdNkF8zb4ZFwxKLIItrorqj4cJzcR   # 你自己的AccessKeySecret
    signName: 乐优商城    # 签名名称
    verifyCodeTemplate: SMS_174024485   # 模板名称
