server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
#  retryable: true
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    search-service: /search/** # 将商品搜索微服务映射到/search/**
#    user-service: /user/** # 将用户微服务映射到/user/**
#    auth-service: /auth/** # 将授权微服务映射到/auth/**
#    cart-service: /cart/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：10000ms

ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
